name: example
description: A new Flutter application.
version: 1.1.0+2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ripple_backdrop_animate_route:
    path: ../

flutter:
  uses-material-design: true
